apiVersion: apps/v1
kind: Deployment

metadata:
  name: project-microservice
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: project-microservice

  template:
    metadata:
      labels:
        app: project-microservice

    spec:
      containers:
        - name: project-microservice

          {{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8081

          readinessProbe:
            httpGet:
              path: /api/projects
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/projects
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
