name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - 'release/**'

  pull_request:

jobs:
  build-test:
    name: Build and Test
    uses: ./.github/workflows/build-test.yml

  semgrep:
    name: Semgrep SAST
    needs: build-test
    uses: ./.github/workflows/scan-semgrep.yml

  trivy:
    name: Trivy scan
    needs: build-test
    uses: ./.github/workflows/scan-trivy.yml

  sonarqube:
    name: SonarQube code quality
    needs: build-test
    uses: ./.github/workflows/scan-sonarqube.yml
    secrets: inherit

  build-image:
    name: Build & Push Image to ECR
    needs: build-test
    uses: ./.github/workflows/build-image.yml
    secrets: inherit

  deploy-preview:
    name: Create Ephemeral Environment
    needs: build-image
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy-preview.yml
    secrets: inherit

  cleanup-preview:
    name: Delete Ephemeral Environment
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/cleanup-preview.yml
    secrets: inherit