name: Cleanup Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    name: Delete Ephemeral Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: Rubitor5/TFM-UNIR
          token: ${{ secrets.GH_TOKEN }}

      - name: Remove preview env
        run: |
          PR=${{ github.event.number }}
          rm -f gitops/preview-envs/pr-${PR}.yaml

      - name: Commit cleanup
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "cleanup PR-${{ github.event.number }}" || exit 0
          git push