name: Trivy scan

on:
  workflow_call:
    inputs:
      scan_ref:
        description: Path to scan
        required: false
        type: string
        default: project-microservice

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-${{ runner.os }}

      - name: Run Trivy scan (safe CI mode)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ${{ inputs.scan_ref }}

          format: json
          output: trivy-results.json

          scanners: vuln,secret

          ignore-unfixed: true
          exit-code: '0'

          skip-files: "**/*.pom,**/pom.xml"
          skip-dirs: "**/.m2,**/target"

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.json